### ISSUE TITLE
Jacobian sparsity pattern

### ISSUE THREAD

**Issue by kossikater** [modelon-community/Assimulo#11]
It would be great if the solvers could use a Jacobian sparsity pattern indicating which entries are zero for sure, similar to `scipy`'s `solve_ivp`. This could increase speed for calculations on approximating the Jacobian is no analytical one is supplied.

**Comment by chria** [comment]
Hi! I agree, however, this is currently not possible. What you can do instead is to override the Jacobian function in the problem definition and there implement (either and FD or AD scheme) that takes into account the sparsity pattern.

**Comment by swsyoon** [comment]
@chria Is it possible for you to create a simple example of how to use AD scheme to provide Jacobian for sundials solver such as IDA or CVODE ? I am using casadi python version to provide symbolic jacobian and try to use it in 'ida_with_jac.py' example but I keep getting errors such as f function return type error or Jacobian function is not callable
