### ISSUE TITLE
Current assimulo version 3.2 raises numpy deprecation warning for odepack.py, l 701

### ISSUE THREAD

**Issue by kossikater** [modelon-community/Assimulo#13]
![image](https://user-images.githubusercontent.com/12471900/94297730-46090f00-ff65-11ea-9a6d-bb043bc58800.png)
Hi there,
I just created a new conda environment with the current assimulo 3.2, and I got a deprecation warning from numpy as you can see in the snippet.
Seems like this should be taken care some day.
Best and many thanks

**Comment by modelonrobinandersson** [comment]
Hi @kossikater I am closing this issue since it has been resolved in a newer version. Thank you for reporting it.
