### ISSUE TITLE
AttributeError: 'Assimulo_prepare' object has no attribute 'sundials_with_msvc'

### ISSUE THREAD

**Issue by pswpswpsw** [modelon-community/Assimulo#18]
I tried to install from source code: 
```
python setup.py install --user
```
Then it pops up the following error
```
  tree = Parsing.p_module(s, pxd, full_module_name)
Traceback (most recent call last):
  File "setup.py", line 610, in <module>
    ext_list = prepare.cython_extensionlists()
  File "setup.py", line 518, in cython_extensionlists
    if self.sundials_with_msvc:
AttributeError: 'Assimulo_prepare' object has no attribute 'sundials_with_msvc'
```

**Comment by apigott** [comment]
Hi @pswpswpsw did you ever figure this out? I have the same error

**Comment by ChristophGehbauer** [comment]
Same issue here. Versions up to 3.0 work, everything beyond throes this error for me (Ubuntu 18.04, Python3.6).
Thanks!

**Comment by apigott** [comment]
Hi @ChristophGehbauer did you ever get this working? For me this was an issue with not finding the sundials library at all. An outtake from the Dockerfile I used that works:

```conda install -n myenv -c conda-forge sundials &&\
  wget https://github.com/modelon-community/Assimulo/archive/Assimulo-3.2.4.tar.gz &&\
  tar xfz Assimulo-3.2.4.tar.gz &&\
  cd Assimulo-Assimulo-3.2.4 &&\
  python setup.py install --sundials-home=/opt/intel/oneapi/intelpython/latest/envs/myenv --lapack-home=/usr/lib/x86_64-linux-gnu/ --blas-home=/usr/lib/x86_64-linux-gnu/ &&\```

Did you try looking in <sundials-home>/include/ for cvode and cvodes?

**Comment by ChristophGehbauer** [comment]
Thank you @apigott, that was a good hint. I didn't install Sundials in the default directory ```/usr/local```, which caused the ```setup.py``` to throw this error.

Would suggest to review the ```check_SUNDIALS``` function and subsequent usage of the ```self.sundials_with_msvc``` to avoid the crash, and rather catch this issue.

**Comment by chria** [comment]
I've updated the setup script so that this does not occur.
