### ISSUE TITLE
Numpy deprecation warning with IDA

### ISSUE THREAD

**Issue by kossikater** [modelon-community/Assimulo#48]
Hi, when running simulations with IDA, I get a numpy deprecation warning, see screenshot.

Best

![image](https://user-images.githubusercontent.com/12471900/203824652-7fef194e-da34-4a74-ad91-e3a0fffb65aa.png)

**Comment by PeterMeisrimelModelon** [comment]
https://github.com/modelon-community/Assimulo/pull/49
