### ISSUE TITLE
Python 3.12 support

### ISSUE THREAD

**Issue by jschueller** [modelon-community/Assimulo#70]
numpy.distutils was removed with 3.12 so assimulo cannot be built anymore

possible migration paths include scikit-build-core or meson, unless remaining Fortran sources could be removed so that setuptools can be kept
https://numpy.org/doc/stable/reference/distutils_status_migration.html

**Comment by modelonrobinandersson** [comment]
Hi @jschueller, thank you for raising this. I think we have to do some major restructuring of both `assimulo` and `pyfmi`, I'd like to discuss this further with @chria before we do anything. This will likely take some time I'll keep updating this thread (as well as the PyFMI one)

**Comment by jschueller** [comment]
what about scikit-build-core ? this seems neat, see #93

**Comment by modelonrobinandersson** [comment]
Hi @jschueller I think scikit-build-core is likely the way to go too. I have just briefly looked at it but it seems like the most viable approach forward.
We just merged a day ago support for Cython 3.x which likely will simplify the process a bit.
