### ISSUE TITLE
MPI error with Assimulo 3.5.1

### ISSUE THREAD

**Issue by jmrohwer** [modelon-community/Assimulo#99]
I have compiled and installed Assimulo 3.5.1 on an Arch linux system using the command:
```shell
python setup.py install --sundials-home=/usr --blas-home=/usr/lib --lapack-home=/usr
```
This is in a fresh Python 3.11 (compiled from scratch) virtual environment. The module compiles without error.

Some of the examples fail with the following error:
```shell
➜ python cvode_basic.py               
*** The MPI_Comm_dup() function was called before MPI_INIT was invoked.
*** This is disallowed by the MPI standard.
*** Your MPI job will now abort.
[jr-xps13:342153] Local abort before MPI_INIT completed completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
```

Specifically, only the examples with `cvode`, `ida` and `kinsol` fail with this error. All other examples (dasp,3, dopri5, radau5, etc.) work as expected.

I did not specify any MPI options during the compile, but `openmpi` and `python-mpi4py` packages are installed on my system (although the latter is based on the system Python 3.12, and I compiled this in a virtual environment with Python 3.11).

Is this a bug or am I doing something wrong?

**Versions**
- openblas 0.3.26
- sundials 7.0.0

**Comment by jmrohwer** [comment]
- numpy 1.26.4
- Cython 3.0.10

I can compile and run Assimulo 3.4.3 without error (using cython 0.29 and against sundials 6.7.0).

**Comment by PeterMeisrimelModelon** [comment]
Can you try Assimulo 3.5.1 with sundials 6.7.0?

**Comment by jmrohwer** [comment]
Assimulo 3.5.1 with sundials 6.7.0 works perfectly :smiley:

**Comment by PeterMeisrimelModelon** [comment]
@jschueller Do you want to have a look at this, seems like there are still some issues with Sundials 7?

**Comment by jschueller** [comment]
sundials must be compiled without mpi support

**Comment by jmrohwer** [comment]
Okay, this was the distro provided version, I don't really need 7.0, so will stick with 6.7 as that works. Thanks for the help!
